/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   utils.c                                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: fde-alme <fde-alme@student.42porto.com>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/06/09 01:27:51 by fde-alme          #+#    #+#             */
/*   Updated: 2025/06/09 01:28:39 by fde-alme         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "pipex.h"

/* Frees arrays generated by the ft_split used in the program. */

void	free_split(char **arr)
{
	size_t	i;

	i = 0;
	if (!arr)
		return ;
	while (arr[i])
	{
		free(arr[i]);
		arr[i] = NULL;
		i++;
	}
	free(arr);
}

/* Tries to open the OUTPUT file, in append or normal mode.
 * if it fails, terminates the program with an error. */

int	open_output(char *filename, int append)
{
	int	fd;

	if (append)
		fd = open(filename, O_CREAT | O_APPEND | O_WRONLY, 0644);
	else
		fd = open(filename, O_CREAT | O_TRUNC | O_WRONLY, 0644);
	if (fd == -1)
	{
		ft_dprintf(2, "pipex: %s: %s\n", strerror(errno), filename);
		error();
	}
	return (fd);
}

/* Tries to open the INPUT file, and redirects STDIN to it. 
 * if it fails, terminates the program with an error. */

int	open_input(char *file_path)
{
	int	fd;

	fd = open(file_path, O_RDONLY);
	if (fd == -1)
	{
		ft_dprintf(2, "pipex: %s: %s\n", strerror(errno), file_path);
		fd = open("/dev/null", O_RDONLY);
		if (fd == -1)
			error();
	}
	dup2(fd, STDIN_FILENO);
	close(fd);
	return (fd);
}

/* Calls exit function with different types of error codes. */

void	error(void)
{
	if (errno == ENOENT)
		exit(127);
	else
		exit(EXIT_FAILURE);
}

/* Extracts the PATH line from envp, then split it in an array of paths 
 * Ex: ["/usr/local/bin", "/usr/bin"...] */

char	**extract_paths_envp(char *envp[])
{
	char	**paths;
	char	*env_path;

	paths = NULL;
	env_path = NULL;
	while (*envp && !env_path)
	{
		if (ft_strncmp(*envp, "PATH=", 5) == 0)
		{
			env_path = *envp + 5;
			break ;
		}
		envp++;
	}
	if (env_path)
		paths = ft_split(env_path, ':');
	return (paths);
}
